[package]
name = "semqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
color-backtrace = "0.6.1"
cryptoki = "0.8.0"
pretty_env_logger = "0.5.0"
rumqttc = "0.24.0"
rustls = { version = "0.23.21", default-features = false, features = [
    "ring"
]}
tokio = "1.43.0"
