name: build-container

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version"
        type: string
        default: "latest"

jobs:
  push:
    runs-on: ${{ matrix.job.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        job:
          - { platform: linux/arm64, image: "experiment-tedge-container-bundle-arm64", runner: "ubuntu-24.04-arm" }
          - { platform: linux/amd64, image: "experiment-tedge-container-bundle-amd64", runner: "ubuntu-latest" }

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: taiki-e/install-action@just

      - name: Publish images
        run: just PLATFORMS=${{ matrix.job.platform }} IMAGE=${{ matrix.job.image }} publish registry ${{ inputs.VERSION || github.ref_name }}
        working-directory: ./tedge
